AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EC2 instance by AWS CloudFormation
Resources:
  SecurityGroupDemoSvrTraffic:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: sgDemoSvr
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
        Description: For traffic from Internet
      GroupDescription: Security Group for demo server
      VpcId: vpc-0e7784bb8fe8fe84a
  EC2InstanceDemoSvr:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1b
      BlockDeviceMappings:
      - DeviceName: "/dev/sda1"
        Ebs:
          DeleteOnTermination: 'true'
          VolumeSize: '8'
          VolumeType: gp2
      ImageId: ami-08c40ec9ead489470
      InstanceType: t2.micro
      KeyName: ec2-demo
      NetworkInterfaces:
      - Description: Primary network interface
        DeviceIndex: '0'
        SubnetId: subnet-03a36e4a6c6d4a435
        PrivateIpAddress: 172.31.16.4
        GroupSet:
        - Ref: SecurityGroupDemoSvrTraffic